Repository SU-SOE/engineering_profile, pull requests merged in 2021-07, with the labels that each got.

#8 SOED9-109 - pulled files form SOED9-91 to skirt having to merge.
  config/sync/field.storage.node.su_news_banner_media_caption.yml
  config/sync/field.storage.node.su_news_dek.yml
  config/sync/migrate_plus.migration.soe_news_test_d7_images.yml
  config/sync/migrate_plus.migration.soe_news_test_d7_media.yml
  config/sync/migrate_plus.migration.soe_test_news_d7_node.yml
  config/sync/migrate_plus.migration.soe_test_news_d7_paragraphs.yml
  config/sync/migrate_plus.migration_group.media.yml
  config/sync/migrate_plus.migration_group.news_items_d7.yml
Labels: size/s

#13 Corrected the events schedule display settings for the pattern refactor
  config/sync/colorbox.settings.yml
  config/sync/core.entity_view_display.paragraph.stanford_media_caption.default.yml
  config/sync/core.extension.yml
  config/sync/editor.editor.stanford_html.yml
  config/sync/field.field.media.stanford_gallery_images.su_gallery_image.yml
  config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_link.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/mathjax.settings.yml
  config/sync/views.view.stanford_person.yml
  config/sync/views.view.stanford_person_list_terms_first.yml
  config/sync/views.view.stanford_publications.yml
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/functional/Paragraphs/GalleryCest.php
Labels: size/xs

#12 SOED9-110 - rebranched from lastest changes to avoid merge conflcts.
  config/sync/migrate_plus.migration.soe_stanford_pages_d7_node.yml
  config/sync/migrate_plus.migration.soe_stanford_pages_d7_paragraph_rows.yml
  config/sync/migrate_plus.migration.soe_stanford_pages_d7_paragraphs.yml
  config/sync/migrate_plus.migration_group.stanford_pages_d7.yml
Labels: size/s

#15 test fixup
  tests/codeception/acceptance/Content/PersonCest.php
Labels: size/xs

#17 added field configs
  config/sync/core.base_field_override.node.spotlight.title.yml
  config/sync/core.entity_form_display.node.spotlight.default.yml
  config/sync/core.entity_view_display.node.spotlight.default.yml
  config/sync/core.entity_view_display.node.spotlight.teaser.yml
  config/sync/field.field.node.spotlight.body.yml
  config/sync/field.field.node.spotlight.su_soe_department.yml
  config/sync/field.field.node.spotlight.su_spotlight_affiliation.yml
  config/sync/field.field.node.spotlight.su_spotlight_degrees.yml
  config/sync/field.field.node.spotlight.su_spotlight_feature_image.yml
  config/sync/field.field.node.spotlight.su_spotlight_person_title.yml
  config/sync/field.field.node.spotlight.su_spotlight_quote.yml
  config/sync/field.storage.node.su_spotlight_affiliation.yml
  config/sync/field.storage.node.su_spotlight_degrees.yml
  config/sync/field.storage.node.su_spotlight_feature_image.yml
  config/sync/field.storage.node.su_spotlight_person_title.yml
  config/sync/field.storage.node.su_spotlight_quote.yml
  config/sync/node.type.spotlight.yml
  config/sync/rabbit_hole.behavior_settings.node_type_spotlight.yml
  config/sync/taxonomy.vocabulary.affiliation.yml
  modules/custom/engineering_profile_helper/content/taxonomy_term/238736c6-516b-4092-835d-b61b4da8b14e.yml
  modules/custom/engineering_profile_helper/content/taxonomy_term/27ce72b5-b9a3-4554-9a18-a1c6cae2f904.yml
  modules/custom/engineering_profile_helper/content/taxonomy_term/730b3511-5e34-4257-b2da-cdf3afeba625.yml
  modules/custom/engineering_profile_helper/content/taxonomy_term/7ed3e65f-e2db-419b-88c7-8a14cba063dc.yml
  modules/custom/engineering_profile_helper/content/taxonomy_term/7ff7a24b-2afc-4e8d-bd65-9c051261af33.yml
  modules/custom/engineering_profile_helper/content/taxonomy_term/a9fdf582-b3ac-4c05-8d40-f6113c60f082.yml
  tests/codeception/acceptance/Content/EngineeringVocabulariesCest.php
Labels: size/m

#21 Magazine migrations
  config/sync/migrate_plus.migration.magazine_items_d7_images.yml
  config/sync/migrate_plus.migration.magazine_items_d7_media.yml
  config/sync/migrate_plus.migration.magazine_items_d7_node.yml
  config/sync/migrate_plus.migration.magazine_items_paragraphs_d7.yml
  config/sync/migrate_plus.migration_group.magazine_items_d7.yml
Labels: size/s

#22 D8CORE-2594 Allow menu placement under unpublished pages (#435)
  CHANGELOG.md
  config/sync/mathjax.settings.yml
  engineering_profile.info.yml
  tests/codeception/functional/Contrib/ExtLinkCest.php
Labels: size/xs

#24 FIXUP! - added format for Spotlight Story.
  config/sync/migrate_plus.migration.soe_people_spotlight_d7_node.yml
Labels: size/xs

#25 FIXUP! - added pathauto and path alias processes.
  config/sync/migrate_plus.migration.soe_people_spotlight_d7_node.yml
Labels: size/xs

#26 FIXUP: point to engineering XML feed instead of prod.
  config/sync/migrate_plus.migration.magazine_items_d7_images.yml
  config/sync/migrate_plus.migration.magazine_items_d7_media.yml
  config/sync/migrate_plus.migration.magazine_items_d7_node.yml
  config/sync/migrate_plus.migration.magazine_items_paragraphs_d7.yml
Labels: size/xs
