Repository SU-SOE/engineering_profile, pull requests merged in 2021-09, with the labels that each got.

#36 removed debugging code
  modules/custom/engineering_profile_helper/modules/engineering_magazine/dist/js/engineering_magazine.script.js
  modules/custom/engineering_profile_helper/modules/engineering_magazine/dist/js/engineering_magazine.script.js.map
  modules/custom/engineering_profile_helper/modules/engineering_magazine/lib/js/magazine_navigation.js
  modules/custom/engineering_profile_helper/modules/engineering_magazine/src/Plugin/Block/MagazineCurtainBlock.php
  themes/engineering/dist/js/engineering.script.js
  themes/engineering/dist/js/engineering.script.js.map
  themes/engineering/lib/js/engineering.behavior.js
Labels: size/xs

#37 FIXUP - removing misspelled utilities dir and fixed dropdown identifiers.
  modules/custom/engineering_profile_helper/engineering_profile_helper.module
  modules/custom/engineering_profile_helper/modules/engineering_magazine/src/Plugin/Block/MagazineCurtainBlock.php
  themes/engineering/lib/scss/components/banner/_spotlight-node-banner.scss
  themes/engineering/lib/scss/components/card/_spotlight-card.scss
  themes/engineering/lib/scss/components/form/_dropdown.scss
  themes/engineering/lib/scss/engineering.scss
  themes/engineering/lib/scss/page/_quote.scss
  themes/engineering/lib/scss/utilities/mixins/_typography.scss
  themes/engineering/lib/scss/utilities/mixins/index.scss
  themes/engineering/lib/scss/utilities/variables/_colors.scss
  themes/engineering/lib/scss/utilities/variables/_typography.scss
  themes/engineering/lib/scss/utilities/variables/index.scss
  themes/engineering/lib/scss/utlities/mixins/index.scss
Labels: size/xs

#40 SOED9-17 - adding printing stylesheet
  composer.json
  config/install/.htaccess
  config/sync/.htaccess
  config/sync/block.block.engineering_branding.yml
  config/sync/block.block.engineering_config_pages_local_footer.yml
  config/sync/block.block.engineering_config_pages_stanford_global_msg.yml
  config/sync/block.block.engineering_config_pages_stanford_super_footer.yml
  config/sync/block.block.engineering_content.yml
  config/sync/block.block.engineering_help.yml
  config/sync/block.block.engineering_local_tasks.yml
  config/sync/block.block.engineering_main_navigation.yml
  config/sync/block.block.engineering_messages.yml
  config/sync/block.block.engineering_pagetitle.yml
  config/sync/block.block.engineering_search.yml
  config/sync/block.block.engineering_search_form.yml
  config/sync/block.block.views_block__spotlights_block_3.yml
  config/sync/core.entity_view_mode.node.printable.yml
  config/sync/core.extension.yml
  config/sync/printable.settings.yml
  config/sync/user.role.anonymous.yml
  themes/engineering/dist/css/engineering.components.css
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/dist/css/print.styles.css
  themes/engineering/dist/js/engineering.script.js
  themes/engineering/dist/js/engineering.script.js.map
  themes/engineering/engineering.info.yml
  themes/engineering/engineering.libraries.yml
  themes/engineering/lib/js/engineering-stanford-news-override.behavior.js
  themes/engineering/lib/js/engineering.js
  themes/engineering/lib/scss/components/index.scss
  themes/engineering/lib/scss/components/social-media/_news-print.scss
  themes/engineering/lib/scss/components/social-media/index.scss
  themes/engineering/lib/scss/page/_news.scss
  themes/engineering/lib/scss/page/index.scss
  themes/engineering/lib/scss/print.scss
  themes/engineering/lib/scss/print/_news-print.scss
  themes/engineering/lib/scss/print/index.scss
  themes/engineering/package-lock.json
  themes/engineering/package.json
  themes/engineering/templates/page/templates/printable.html.twig
  themes/engineering/templates/sections/print/printable--one-column.html.twig
  themes/engineering/templates/sections/print/printable-footer.html.twig
  themes/engineering/templates/sections/print/printable-header.html.twig
  themes/engineering/webpack.config.js
Labels: size/m

#42 FIXUp - set site to no-follow.
  config/sync/metatag.metatag_defaults.global.yml
Labels: size/xs

#44 SOED9-148 - created layout template and exported build layout
  config/sync/block.block.engineering_pagetitle.yml
  config/sync/block.block.stanford_basic_pagetitle.yml
  config/sync/core.entity_view_display.node.spotlight.default.yml
  config/sync/core.entity_view_display.node.spotlight.spotlights_hero.yml
  config/sync/core.entity_view_display.node.spotlight.teaser.yml
  config/sync/core.entity_view_mode.block_content.spotlight_hero.yml
  config/sync/core.entity_view_mode.node.spotlights_hero.yml
  config/sync/page_manager.page.spotlights.yml
  config/sync/views.view.spotlights.yml
  themes/engineering/dist/css/engineering.components.css
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/dist/js/engineering.script.js
  themes/engineering/engineering.layouts.yml
  themes/engineering/engineering.theme
  themes/engineering/lib/js/engineering.behavior.js
  themes/engineering/lib/js/engineering.js
  themes/engineering/lib/scss/base/_print-link.scss
  themes/engineering/lib/scss/base/index.scss
  themes/engineering/lib/scss/components/banner/_spotlight-node-banner.scss
  themes/engineering/lib/scss/components/banner/index.scss
  themes/engineering/lib/scss/components/button/_button.scss
  themes/engineering/lib/scss/components/button/_spotlight-apply.scss
  themes/engineering/lib/scss/components/button/index.scss
  themes/engineering/lib/scss/components/card/_spotlight-card.scss
  themes/engineering/lib/scss/components/card/_spotlight-card__banner.scss
  themes/engineering/lib/scss/components/form/_dropdown.scss
  themes/engineering/lib/scss/components/form/index.scss
  themes/engineering/lib/scss/components/index.scss
  themes/engineering/lib/scss/components/quote/_quote.scss
  themes/engineering/lib/scss/components/quote/index.scss
  themes/engineering/lib/scss/components/social-media/_news-print.scss
  themes/engineering/lib/scss/components/social-media/index.scss
  themes/engineering/lib/scss/engineering.scss
  themes/engineering/lib/scss/layout/blocks/index.scss
  themes/engineering/lib/scss/layout/index.scss
  themes/engineering/lib/scss/page/index.scss
  themes/engineering/lib/scss/page/spotlight/_main-content.scss
  themes/engineering/lib/scss/page/spotlight/_quote.scss
  themes/engineering/lib/scss/page/spotlight/_related-spotlight.scss
  themes/engineering/lib/scss/page/spotlight/index.scss
  themes/engineering/lib/scss/print/_news-print.scss
  themes/engineering/lib/scss/utilities/index.scss
  themes/engineering/lib/scss/utilities/variables/_fonts.scss
  themes/engineering/lib/scss/utilities/variables/index.scss
  themes/engineering/templates/component/container--more-link--spotlights--block-3.html.twig
  themes/engineering/templates/component/field--node--created--spotlight.html.twig
  themes/engineering/templates/sections/spotlight-header-layout.html.twig
Labels: size/l

#38 Removed equal heights from spotlight and magazine card grids
  CHANGELOG.md
  composer.json
  config/sync/block.block.engineering_pagetitle.yml
  config/sync/core.entity_view_display.taxonomy_term.magazine_issues.default.yml
  config/sync/core.entity_view_display.taxonomy_term.magazine_topics.default.yml
  config/sync/core.extension.yml
  config/sync/engineering.settings.yml
  config/sync/field.field.node.stanford_event.su_event_components.yml
  config/sync/field.field.node.stanford_news.su_news_components.yml
  config/sync/field.field.node.stanford_person.su_person_components.yml
  config/sync/field.field.paragraph_row.node_stanford_page_row.su_page_components.yml
  config/sync/migrate_plus.migration.magazine_items_d7_images.yml
  config/sync/migrate_plus.migration.soe_news_test_d7_images.yml
  config/sync/migrate_plus.migration.soe_people_spotlight_d7_images.yml
  config/sync/page_manager.page.magazine_issue_list_page.yml
  config/sync/page_manager.page_variant.magazine_issue_list_page-layout_builder-0.yml
  config/sync/page_manager.page_variant.magazine_landing_page-layout_builder-0.yml
  config/sync/system.action.media_edit_action.yml
  config/sync/system.action.node_edit_action.yml
  config/sync/system.action.taxonomy_term_edit_action.yml
  config/sync/system.action.user_edit_action.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.content.yml
  config/sync/views.view.magazine.yml
  engineering_profile.info.yml
  modules/custom/engineering_profile_helper/modules/engineering_magazine/dist/css/engineering_magazine.styles.css
  modules/custom/engineering_profile_helper/modules/engineering_magazine/lib/scss/components/index.scss
  modules/custom/engineering_profile_helper/modules/engineering_magazine/lib/scss/components/magazine/_magazine.scss
  modules/custom/engineering_profile_helper/modules/engineering_magazine/lib/scss/components/magazine/index.scss
  modules/custom/engineering_profile_helper/modules/engineering_magazine/lib/scss/components/magazine_curtain/_magazine-curtain.scss
  modules/custom/engineering_profile_helper/modules/engineering_magazine/src/Plugin/Block/MagazineCurtainBlock.php
  modules/custom/engineering_profile_helper/modules/engineering_magazine/src/Plugin/Block/MagazineNavigationBlock.php
  modules/custom/engineering_profile_helper/modules/engineering_magazine/templates/magazine-curtain-block.html.twig
  modules/custom/engineering_profile_helper/src/Plugin/migrate/process/MagazineArticlesToIssues.php
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  tests/codeception/acceptance/Magazine/MagazineBlocksCest.php
  tests/codeception/functional/Paragraphs/AccordionCest.php
  tests/src/Kernel/Plugin/Block/MagazineCurtainBlockTest.php
  tests/src/Kernel/Plugin/Block/MagazineNavigationBlockTest.php
  tests/src/Kernel/Plugin/Block/MagazineTestBase.php
  tests/src/Kernel/Plugin/migrate/process/MagazineArticlesToIssuesTest.php
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/dist/js/engineering.script.js
  themes/engineering/lib/js/engineering.behavior.js
  themes/engineering/lib/scss/engineering.scss
  themes/engineering/lib/scss/utilities/mixins/grid/_magazine-card-grid.scss
Labels: size/l

#23 Added Typogrify module and associated configs
  composer.json
  config/sync/core.extension.yml
  config/sync/editor.editor.stanford_minimal_html.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/filter.format.stanford_minimal_html.yml
  tests/codeception/acceptance/SuperFooter/SuperFooterCest.php
Labels: size/s

#46 Added a check to make sure the "more" link exists before modifying it.
  themes/engineering/engineering.theme
Labels: size/xs

#48 FIXUP (SOED9-17) added import that somehow got lost in the merge.
  themes/engineering/dist/js/engineering.script.js
  themes/engineering/lib/js/engineering.js
Labels: size/xs

#50 FIXUP - updating button link on related spotlight.
  config/sync/views.view.spotlights.yml
Labels: size/xs

#51 SOED9-8 - added permissions for editors and contributors.
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
Labels: size/xs

#47 Article Collections configs and styles
  config/sync/block.block.engineering_pagetitle.yml
  config/sync/core.entity_form_display.taxonomy_term.article_collection.default.yml
  config/sync/core.entity_view_display.taxonomy_term.article_collection.default.yml
  config/sync/field.field.taxonomy_term.article_collection.su_term_components.yml
  config/sync/field.storage.taxonomy_term.su_term_components.yml
  config/sync/filter.format.stanford_minimal_html.yml
  config/sync/migrate_plus.migration.magazine_items_d7_images.yml
  config/sync/migrate_plus.migration.magazine_items_d7_media.yml
  config/sync/migrate_plus.migration.magazine_items_d7_node.yml
  config/sync/migrate_plus.migration.magazine_items_paragraphs_d7.yml
  config/sync/migrate_plus.migration.soe_news_test_d7_images.yml
  config/sync/migrate_plus.migration.soe_news_test_d7_media.yml
  config/sync/migrate_plus.migration.soe_test_news_d7_node.yml
  config/sync/migrate_plus.migration.soe_test_news_d7_paragraphs.yml
  config/sync/pathauto.pattern.article_collections.yml
  config/sync/views.view.magazine_article_collection.yml
  modules/custom/engineering_profile_helper/src/Plugin/migrate/process/FeaturedProcess.php
  modules/custom/engineering_profile_helper/src/Plugin/migrate/process/TruncateString.php
  modules/custom/engineering_profile_helper/src/Plugin/migrate/process/UTF8Convert.php
  tests/src/Unit/Plugin/migrate/process/FeaturedProcessTest.php
  tests/src/Unit/Plugin/migrate/process/TruncateStringTest.php
  tests/src/Unit/Plugin/migrate/process/UTF8ConvertTest.php
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/dist/js/engineering.script.js
  themes/engineering/lib/js/engineering.behavior.js
  themes/engineering/lib/scss/engineering.scss
  themes/engineering/lib/scss/page/article_collection/article_collection.scss
  themes/engineering/lib/scss/page/article_collection/index.scss
  themes/engineering/lib/scss/page/index.scss
Labels: size/l

#49 SOED9-136: Work for the responsive views of the spotlights page.
  config/sync/page_manager.page_variant.spotlights-layout_builder-0.yml
  config/sync/views.view.spotlights.yml
  themes/engineering/dist/css/engineering.components.css
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/dist/css/print.styles.css
  themes/engineering/dist/js/engineering.script.js
  themes/engineering/engineering.theme
  themes/engineering/lib/scss/components/banner/_spotlight-node-banner.scss
  themes/engineering/lib/scss/components/card/_spotlight-card.scss
  themes/engineering/lib/scss/components/card/_spotlight-card__banner.scss
  themes/engineering/lib/scss/components/form/_dropdown.scss
  themes/engineering/lib/scss/components/quote/_quote.scss
Labels: size/l

#52 Article collection fixup
  config/sync/views.view.magazine_article_collection.yml
  themes/engineering/dist/css/engineering.components.css
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/dist/css/print.styles.css
  themes/engineering/dist/js/engineering.script.js
  themes/engineering/lib/js/engineering.js
  themes/engineering/lib/scss/page/article_collection/article_collection.scss
  themes/engineering/package-lock.json
  themes/engineering/webpack.config.js
Labels: size/xl

#54 FIXUP - disabled metatag's nofollow, noindex
  config/sync/metatag.metatag_defaults.global.yml
Labels: size/xs

#56 Adding alias for spotlight nodes.
  config/sync/pathauto.pattern.spotlight_nodes.yml
Labels: size/xs

#58 SOED9-146: fixing the roboto font on the quote
  themes/engineering/dist/css/engineering.components.css
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/dist/css/print.styles.css
  themes/engineering/dist/js/engineering.script.js
  themes/engineering/lib/scss/components/card/_spotlight-card.scss
  themes/engineering/lib/scss/engineering.scss
Labels: size/l

#59 stopped updating body copy to prevent overwriting new work
  .codeclimate.yml
  config/sync/imagemagick.settings.yml
  config/sync/migrate_plus.migration.magazine_items_d7_images.yml
  config/sync/migrate_plus.migration.magazine_items_d7_media.yml
  config/sync/migrate_plus.migration.magazine_items_d7_node.yml
  config/sync/migrate_plus.migration.soe_news_test_d7_images.yml
Labels: size/xs

#55 SOED9-139 - adding tests from new cut branch.
  tests/codeception/acceptance/Content/SpotlightCest.php
Labels: size/xs

#61 Added related departments to the magazine news stories
  config/sync/core.entity_view_display.node.stanford_news.default.yml
  config/sync/core.entity_view_display.taxonomy_term.department.default.yml
  config/sync/views.view.department_terms.yml
  themes/engineering/dist/css/engineering.components.css
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/dist/css/print.styles.css
  themes/engineering/dist/js/engineering.script.js
  themes/engineering/lib/scss/components/department-terms/_department_terms.scss
  themes/engineering/lib/scss/components/department-terms/index.scss
  themes/engineering/lib/scss/components/index.scss
Labels: size/l

#62 Forced first character of drop caps to use Roboto
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/lib/scss/engineering.scss
Labels: size/l
