Repository SU-SOE/engineering_profile, pull requests merged in 2025-06, with the labels that each got.

#137 SOEOPS-584 SOEOPS-588 | update spotlight card link and content width
  config/sync/views.view.spotlights.yml
  themes/engineering/dist/css/engineering.components.css
  themes/engineering/dist/css/engineering.script.js
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/lib/js/engineering.behavior.js
  themes/engineering/lib/scss/components/card/_spotlight-card.scss
  themes/engineering/lib/scss/page/spotlight/_main-content.scss
Labels: size/xs

#140 SOEOPS-637 | update spotlight node styles
  themes/engineering/dist/css/engineering.components.css
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/lib/scss/components/banner/_spotlight-node-banner.scss
Labels: size/xs

#142 SOEOPS-618 | add h1 to department taxonomy term pages
  config/sync/core.entity_view_display.taxonomy_term.department.default.yml
Labels: size/xs

#141 SOEOPS-643 SOEOPS-644 SOEOPS-588 | update spotlight quote field, spotlight news card view config, enable metatag, and tweak styles
  config/engineering/metatag.metatag_defaults.node__spotlight.yml
  config/sync/core.entity_form_display.node.spotlight.default.yml
  config/sync/core.entity_view_display.node.spotlight.default.yml
  config/sync/core.entity_view_display.node.spotlight.spotlights_hero.yml
  config/sync/core.entity_view_display.node.spotlight.stanford_card.yml
  config/sync/core.entity_view_display.node.spotlight.teaser.yml
  config/sync/field.field.node.spotlight.su_metatags.yml
  config/sync/field.field.node.spotlight.su_people_spotlight_quote.yml
  config/sync/views.view.spotlights.yml
  themes/engineering/dist/css/engineering.components.css
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/lib/scss/components/card/_spotlight-card.scss
Labels: size/s, size/xs

#143 Fixing up config splits
  config/engineering/jsonapi_extras.jsonapi_resource_config.node--spotlight.yml
  config/engineering/page_manager.page.magazine_issue_list_page.yml
  config/engineering/page_manager.page.magazine_landing_page.yml
  config/sync/page_manager.page_variant.magazine_issue_list_page-layout_builder-0.yml
  config/sync/page_manager.page_variant.magazine_landing_page-layout_builder-0.yml
  config/sync/pathauto.pattern.article_collections.yml
  config/sync/pathauto.pattern.department_terms.yml
  config/sync/pathauto.pattern.magazine_issues.yml
  config/sync/pathauto.pattern.magazine_topics.yml
  config/sync/rabbit_hole.behavior_settings.taxonomy_vocabulary_magazine_topics.yml
Labels: size/m

#144 SOEOPS-656 SOEOPS-594 | update magazine navigation with nav and list html semantics; adjust news layout
  config/engineering/page_manager.page_variant.magazine_landing_page-layout_builder-0.yml
  modules/engineering_profile_helper/modules/engineering_magazine/dist/css/engineering_magazine.styles.css
  modules/engineering_profile_helper/modules/engineering_magazine/lib/scss/components/magazine_navigation/_magazine-navigation.scss
  modules/engineering_profile_helper/modules/engineering_magazine/templates/block/magazine-navigation.html.twig
Labels: size/s

#145 SOEOPS-612 SOEOPS-615 | add magazine topics to news h3 card
  config/sync/core.entity_view_display.node.stanford_news.stanford_h3_card.yml
Labels: size/xs

#146 SOECENT-657 SOECENT-594 | adjust latest news styles and update spotlight metadata
  config/engineering/metatag.metatag_defaults.node__spotlight.yml
  config/engineering/page_manager.page_variant.magazine_landing_page-layout_builder-0.yml
  modules/engineering_profile_helper/modules/engineering_magazine/dist/css/engineering_magazine.styles.css
  modules/engineering_profile_helper/modules/engineering_magazine/lib/scss/components/magazine_navigation/_magazine-navigation.scss
Labels: size/xs

#147 SOEOPS-657 | adjust spotlight metatag description
  config/engineering/metatag.metatag_defaults.node__spotlight.yml
Labels: size/xs

#148 SOEOPS-594 | add margin bottom to news and topics heading, update news, topics, and spotlights responsive card layout
  config/engineering/config_split.patch.core.entity_view_display.taxonomy_term.magazine_topics.default.yml
  config/engineering/page_manager.page_variant.magazine_landing_page-layout_builder-0.yml
  modules/engineering_profile_helper/modules/engineering_magazine/dist/css/engineering_magazine.styles.css
  modules/engineering_profile_helper/modules/engineering_magazine/lib/scss/components/magazine_navigation/_magazine-navigation.scss
  themes/engineering/dist/css/engineering.components.css
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/lib/scss/components/card/_spotlight-card.scss
  themes/engineering/lib/scss/page/magazine/_magazine.scss
Labels: size/s

#149 SOEOPS-594 | adjust spotlight card breakpoint and spotlight metatag title
  config/engineering/metatag.metatag_defaults.node__spotlight.yml
  themes/engineering/dist/css/engineering.components.css
  themes/engineering/dist/css/engineering.styles.css
  themes/engineering/lib/scss/components/card/_spotlight-card.scss
Labels: size/xs

#150 SOEOPS-615 | hide additional external link for vertical news cards with no image
  themes/soe_basic/dist/css/theme.css
  themes/soe_basic/src/scss/theme/_news.scss
Labels: size/xs
